"""
config.py — Configuration for Phase 5 Medical RAG Engine.

Paths, retrieval settings, evidence levels, metadata schemas, and versioning.
"""

from pathlib import Path
from typing import Any, Dict, List

# Base Paths
BASE_DIR: Path = Path(__file__).resolve().parent.parent.parent
RAG_DIR: Path = Path(__file__).resolve().parent

DATA_DIR: Path = RAG_DIR / "data"
RAW_DOCS_DIR: Path = DATA_DIR / "raw_documents"
DB_DIR: Path = RAG_DIR / "vector_db"
REPORTS_DIR: Path = BASE_DIR / "runtime" / "generated"

# Create directories
DATA_DIR.mkdir(parents=True, exist_ok=True)
RAW_DOCS_DIR.mkdir(parents=True, exist_ok=True)
DB_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Manifest Path
MANIFEST_PATH: Path = DATA_DIR / "source_manifest.json"
VECTOR_STORE_PATH: Path = DB_DIR / "vector_index.json"

# RAG Modes
RAG_MODES: List[str] = ["REPORT", "QANDA"]

# Target Diseases
TARGET_DISEASES: List[str] = [
    "Type2_Diabetes",
    "Prediabetes",
    "Obesity",
    "Metabolic_Syndrome",
    "NAFLD",
]

# Evidence Levels (Strict distinction required)
EVIDENCE_LEVELS: Dict[str, str] = {
    "PATIENT_MEASURED": "Patient-measured raw laboratory or sensor data",
    "ML_PREDICTION": "Multimodal AI probabilistic disease risk output",
    "MODEL_XAI": "Feature-level SHAP attribution or meta-learner decision weight",
    "CLINICAL_GUIDELINE": "Established authoritative clinical practice guideline (e.g. ADA, AASLD, WHO)",
    "EMERGING_RESEARCH": "Peer-reviewed observational or translational research (e.g. microbiome association studies)",
    "LLM_EXPLANATION": "Grounded natural language synthesis generated by assistant",
}

# Retrieval Configuration
DEFAULT_TOP_K: int = 5
MAX_CONTEXT_CHUNKS: int = 4
RERANK_CANDIDATE_K: int = 10

# System Disclaimer
RESEARCH_DISCLAIMER: str = (
    "NOTICE: This report and decision-support guidance are generated by a research prototype AI system "
    "trained on synthetic multimodal data. Predictions and explanations do NOT constitute clinical diagnosis "
    "or medical prescription. Always consult a qualified healthcare professional."
)
