"""Initial PostgreSQL Schema

Revision ID: 410a2d151174
Revises: None
Create Date: 2026-08-02 13:43:23.548562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410a2d151174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_audit_resource_composite', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('account_deletion_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('auth_sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('registration_council', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('hospital_affiliation', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('credential_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('health_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_session_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('effective_pathway', sa.String(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('active_modalities', sa.Text(), nullable=False),
    sa.Column('confirmed_features', sa.Text(), nullable=False),
    sa.Column('prediction_snapshot', sa.Text(), nullable=False),
    sa.Column('xai_snapshot', sa.Text(), nullable=True),
    sa.Column('report_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_health_records_created_at'), 'health_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_records_source_session_id'), 'health_records', ['source_session_id'], unique=True)
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_nav', sa.String(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('assessment_date', sa.String(), nullable=False),
    sa.Column('overall_health_score', sa.Float(), nullable=False),
    sa.Column('highest_risk_disease', sa.String(), nullable=False),
    sa.Column('highest_risk_probability', sa.Float(), nullable=False),
    sa.Column('active_pathway', sa.String(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_assessments_patient_id'), 'assessments', ['patient_id'], unique=False)
    op.create_table('consultations',
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assigned_doctor_id', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctor_profiles.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consultation_id')
    )
    op.create_index(op.f('ix_consultations_assigned_doctor_id'), 'consultations', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('doctor_audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_doctor_audit_logs_doctor_id'), 'doctor_audit_logs', ['doctor_id'], unique=False)
    op.create_table('doctor_availability_slots',
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('doctor_user_id', sa.String(), nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('slot_end', sa.String(), nullable=False),
    sa.Column('is_booked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_doctor_availability_slots_doctor_id'), 'doctor_availability_slots', ['doctor_id'], unique=False)
    op.create_table('doctor_credentials',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_doctor_credentials_doctor_id'), 'doctor_credentials', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_credentials_user_id'), 'doctor_credentials', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('patient_user_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('slot_end', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consultation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['doctor_availability_slots.slot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_consultation_id'), 'appointments', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_user_id'), 'appointments', ['patient_user_id'], unique=False)
    op.create_table('consultation_audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consultation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_consultation_audit_logs_consultation_id'), 'consultation_audit_logs', ['consultation_id'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('sender_user_id', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consultation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    op.create_table('consultation_notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('doctor_user_id', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('follow_up_guidance', sa.Text(), nullable=True),
    sa.Column('patient_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consultation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_consultation_notes_consultation_id'), 'consultation_notes', ['consultation_id'], unique=True)
    op.create_table('consultation_shared_records',
    sa.Column('share_id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('shared_at', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consultation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['health_records.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id'),
    sa.UniqueConstraint('consultation_id', 'record_id', name='uq_cons_record')
    )
    op.create_index(op.f('ix_consultation_shared_records_consultation_id'), 'consultation_shared_records', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_shared_records_record_id'), 'consultation_shared_records', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_shared_records_record_id'), table_name='consultation_shared_records')
    op.drop_index(op.f('ix_consultation_shared_records_consultation_id'), table_name='consultation_shared_records')
    op.drop_table('consultation_shared_records')
    op.drop_index(op.f('ix_consultation_notes_consultation_id'), table_name='consultation_notes')
    op.drop_table('consultation_notes')
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_consultation_audit_logs_consultation_id'), table_name='consultation_audit_logs')
    op.drop_table('consultation_audit_logs')
    op.drop_index(op.f('ix_appointments_patient_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_consultation_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctor_credentials_user_id'), table_name='doctor_credentials')
    op.drop_index(op.f('ix_doctor_credentials_doctor_id'), table_name='doctor_credentials')
    op.drop_table('doctor_credentials')
    op.drop_index(op.f('ix_doctor_availability_slots_doctor_id'), table_name='doctor_availability_slots')
    op.drop_table('doctor_availability_slots')
    op.drop_index(op.f('ix_doctor_audit_logs_doctor_id'), table_name='doctor_audit_logs')
    op.drop_table('doctor_audit_logs')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_assigned_doctor_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_assessments_patient_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_source_session_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_created_at'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('account_deletion_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('idx_audit_resource_composite', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
